#!/bin/bash     

#verifica espaco de servidores a partir de uma lista 
while read line
do   
    log='"arquivo.txt" para guardar os resultados'
    echo "********************************" #as duas variaveis a seguir possui parametros para meu uso'
    disk=$(ssh -n $line df -h / | awk '{print $5}' | grep -v Use | head -n2) #uso de disco
    avail=$(ssh -n $line df -h / | awk '{print $4}' | grep -v Avail | head -n4) #espaco livre
    echo "********************" >> $log        
    echo "   $line" >> $log
    echo " Uso de disco: "  $disk >> $log
    echo          >> $log
    echo ""
    echo " Servidor $line"
    echo " Uso de disco: "$disk
    echo " Espaco livre: "$avail
    echo ""    
done < #diretorio da lista

#envia as informações via e-mail
cat $log | mail -s "Espaco dos servidores" <e-mail para qual deseja enviar os dados>

#remove o "arquivo.txt" para nao causar bugs em verificacoes futuras 
rm -r 'diretorio do arquivo.txt'
