#!/bin/bash     

#verifica espaco de servidores a partir de uma lista 
while read line
do   
    log='Arquivo.txt para guardar as informações'
    echo "********************************" #as duas variaveis a seguir possui parametros para meu uso'
    resulta=$(ssh -n $line df -h / | awk '{print $5}' | grep -v Use | head -n2) #uso de disco
    resulta1=$(ssh -n $line df -h / | awk '{print $4}' | grep -v Avail | head -n4) #espaco livre
    echo "********************" >> $log        
    echo "   $line" >> $log
    echo " Uso de disco: "  $resulta >> $log
	echo " Espaco livre: "	$resulta1 >> $log
    echo          >> $log
    echo ""
    echo "  loja $line"
    echo " Uso de disco: "$resulta
    echo " Espaco livre: "$resulta1
    echo "" 
done < 'diretorio da lista de servidores'

cat $log | mail -s "Espaco dos servidores" < e-mail para qual deseja enviar os dados >